# Generated by Django 5.0.6 on 2024-06-04 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Phone number')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Others', 'others')], max_length=10, null=True, verbose_name='Gender')),
                ('religion', models.CharField(blank=True, choices=[('Islam', 'islam'), ('Hindu ', 'hindu'), ('Christian', 'christian'), ('Buddhist', 'buddhist'), ('Others', 'others')], max_length=20, null=True, verbose_name='Religion')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ProfileImage/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verification')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Verification Time')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Phone Verification')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Phone Verification Time')),
                ('is_membership', models.BooleanField(default=False, verbose_name='Membership')),
                ('auth_provider', models.CharField(choices=[('Local', 'local'), ('Google', 'google'), ('Twitter', 'twitter'), ('Facebook', 'facebook'), ('Instagram', 'instagram')], default='Local', max_length=20, verbose_name='Authentication With')),
                ('fcm_device_token', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('otp', models.IntegerField()),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
